# Generated by Django 5.0.1 on 2026-01-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('gluteal', 'Gluteal Region')], default='gluteal', max_length=50)),
                ('scenario', models.CharField(choices=[('projection-level-1', 'Projection Level 1'), ('projection-level-2', 'Projection Level 2'), ('projection-level-3', 'Projection Level 3')], default='projection-level-1', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('simulation1_image', models.ImageField(blank=True, null=True, upload_to='simulations/')),
                ('simulation2_image', models.ImageField(blank=True, null=True, upload_to='simulations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
